# alb variables
variable "project_name" {}
variable "environment" {}
variable "app_server_security_group_id" {}
variable "public_subnet_az1_id" {}
variable "public_subnet_az2_id" {}
variable "target_type" {}
variable "vpc_id" {}
variable "certificate_arn" {}